version: '3'

services:
  bluex-gitlab:
    image: gitlab/gitlab-ce:14.4.4-ce.0
    restart: always
    container_name: gitlab
    hostname: 'git.bluex.fr'
    volumes:
      - gitlab_data:/etc/gitlab
    ports:
      - '8090:80'
      - '2222:22'
volumes:
  gitlab_data:
